# private global parameters class. Do not use directly!
class openstack::config (
  $use_hiera = false,
  $region = 'RegionOne',
  $network_api = "$mgmt_network",
  $networks = undef,
  $subnets = undef,
  $routers = undef,
  $router_interfaces = undef,
  $network_external = undef,
  $network_management = "$mgmt_network",
  $network_data = "$mgmt_network",
  $network_external_ippool_start = undef,
  $network_external_ippool_end = undef,
  $network_external_gateway = undef,
  $network_external_dns = undef,
  $network_neutron_private = undef,
  $controller_address_api = "$ctr_ip",
  $controller_address_management = "$ctr_ip",
  $storage_address_api = "$ctr_ip",
  $storage_address_management = "$ctr_ip",
  $mysql_root_password = 'changeme',
  $mysql_service_password = 'changeme',
  $mysql_allowed_hosts = ["localhost","127.0.0.1","*.${domain}"],
  $mysql_user_keystone = 'keystone',
  $mysql_pass_keystone = 'changeme',
  $mysql_user_cinder = 'cinder',
  $mysql_pass_cinder = 'changeme',
  $mysql_user_glance = 'glance',
  $mysql_pass_glance = 'changeme',
  $mysql_user_nova = 'nova',
  $mysql_pass_nova = 'changeme',
  $mysql_user_neutron = 'neutron',
  $mysql_pass_neutron = 'changeme',
  $mysql_user_heat = 'heat',
  $mysql_pass_heat = 'changeme',
  $rabbitmq_hosts = ["$ctr_ip:5672"],
  $rabbitmq_user = 'openstack',
  $rabbitmq_password = 'guest',
  $keystone_admin_token = 'changeme',
  $keystone_admin_email = 'changeme@demo.com',
  $keystone_admin_password = 'changeme',
  $keystone_tenants = {'test' => { 'description' => 'test_tenant'}},
  $keystone_users = {'test' => {'password' => 'abc123', 'tenant' => 'test', 'email' => 'test@example.com', 'admin' => 'true'}},
  $keystone_use_httpd = true,
  $glance_password = 'changeme',
  $glance_api_servers = ["$ctr_ip:9292"],
  $images = undef,
  $cinder_password = 'changeme',
  $cinder_volume_size = '4G',
  $swift_password = 'changeme',
  $swift_hash_suffix = 'changeme',
  $nova_libvirt_type = $nova_libvirt_type,
  $nova_password = 'changeme',
  $neutron_password = 'changeme',
  $neutron_shared_secret = 'changeme',
  $neutron_core_plugin = 'ml2',
  $neutron_service_plugins = [
  'router',
  'lbaas',
  'firewall',
  'metering',
  ],
  $neutron_tunneling = true,
  $neutron_tunnel_types = ['gre'],
  $neutron_tenant_network_type = ['gre'],
  $neutron_type_drivers = ['gre'],
  $neutron_mechanism_drivers = ['openvswitch'],
  $neutron_tunnel_id_ranges = ['1:1000'],
  $plumgrid_director_vip = undef,
  $plumgrid_username = undef,
  $plumgrid_password = undef,
  $plumgrid_nova_metadata_ip = undef,
  $plumgrid_nova_metadata_port = undef,
  $ceilometer_address_management = "$ctr_ip",
  $ceilometer_mongo_username = 'changeme',
  $ceilometer_mongo_password = 'changeme',
  $ceilometer_password = 'changeme',
  $ceilometer_meteringsecret = 'changeme',
  $heat_password = 'changeme',
  $heat_encryption_key = 'heatsecretkey123',
  $horizon_secret_key = 'changeme',
  $horizon_allowed_hosts = undef,
  $horizon_server_aliases = undef,
  $tempest_configure_images    = undef,
  $tempest_image_name          = undef,
  $tempest_image_name_alt      = undef,
  $tempest_username            = undef,
  $tempest_username_alt        = undef,
  $tempest_username_admin      = undef,
  $tempest_configure_network   = undef,
  $tempest_public_network_name = undef,
  $tempest_cinder_available    = undef,
  $tempest_glance_available    = undef,
  $tempest_horizon_available   = undef,
  $tempest_nova_available      = undef,
  $tempest_neutron_available   = undef,
  $tempest_heat_available      = undef,
  $tempest_swift_available     = undef,
  $verbose = false,
  $debug = false,
) {
}
